# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_bsas_data": "00_core.ipynb",
         "get_bsas_data2": "00_core.ipynb",
         "LassoICSelector.fit": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ababino.github.io/covid19bsas/"

git_url = "https://github.com/ababino/covid19bsas/tree/main/"

def custom_doc_links(name): return None
