# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['get_bsas_data']

# Cell
import pandas as pd

# Cell
def get_bsas_data():
    df = pd.read_csv('https://cdn.buenosaires.gob.ar/datosabiertos/datasets/salud/reporte-covid/dataset_reporte_covid_sitio_gobierno.csv')
    df['Date'] = pd.to_datetime(df.FECHA.map(lambda x:x[:2]+x[2:].capitalize()), format='%d%b%Y:00:00:00')
    df = df.sort_values('Date')
    df = df.loc[df.SUBTIPO_DATO.isin(['personas_hisopadas_reportados_del_dia_totales', '%_positividad_personas_hisopadas_reportadas_del_dia_totales']), ['Date', 'SUBTIPO_DATO', 'VALOR']]
    df = df.set_index(['Date','SUBTIPO_DATO'])['VALOR'].unstack()
    df = df.rename(columns={'personas_hisopadas_reportados_del_dia_totales': 'Tests', '%_positividad_personas_hisopadas_reportadas_del_dia_totales':'p'})
    df.columns.name = ''
    df.p = df.p*0.01
    df['Positives'] = df.p*df.Tests
    df['Negatives'] = df.Tests-df.Positives
    df['Odds'] = df.Positives / df.Negatives
    df = df.reset_index()
    df['date'] = df.Date
    df = df.set_index('date')
    return df